### ISSUE TITLE
Python API example for "Polygon covering multiple land and ice outlets" fails silently

### ISSUE THREAD

**Issue by tarynblack** [GEUS-Glaciology-and-Climate/freshwater#29]
I am attempting to work through the provided examples for the Python API, and have found that the example for "Polygon covering multiple land and ice outlets" fails silently at this line:
`ds = discharge(base="./freshwater", roi="-51.50,66.93 -51.21,66.74 -49.44,66.91 -49.84,67.18", quiet=False, upstream=True).discharge()`
The output makes it this far:
```Using './freshwater' as base folder
Loading discharge data...
    Loading MAR_land
    Loading MAR_ice
    Loading RACMO_land
    Loading RACMO_ice
Loading outlets and basins...
    Loading land
    Loading ice
Subsetting data by ROI...
Parsing ROI...
    ROI appears to be boundary (from points) in EPSG:4326 coordinates
ROI is geometry... finding all points inside geometry
    Finding basins upstream of land basins within ROI
        ice
```
I added some print statements to `discharge.py` and it appears that it is failing in `subset_to_ROI` between lines 197-211 (when subsetting data to be within the provided polygon). The example also fails when `upstream=False`.

I am running this in a Jupyter notebook in VS Code with Python v3.8.5. Let me know if I can provide any other information - this is my first time submitting an issue!

**Comment by mankoff** [comment]
Hi @tarynblack  - I've seen this before when a machine runs out of RAM. How much RAM is on your machine? 

When I run this on the CLI  (with `python ./discharge.py --base ~/data/Mankoff_2020/water --roi="-51.50,66.93 -51.21,66.74 -49.44,66.91 -49.84,67.18" -d`) my machine uses just over 12 GB (monitor w/ `htop` or some other tool) for this + other OS stuff, but it prints out the expected 4 columns (plus the date column). 

When I add `-u` to get upstream ice for each land outlet, RAM usage is about the same - an extra ~1 to 1.5 GB and prints 8+1 columns.

When I run it in Python, usage is about the same.

Note - if you include upstream outlets, be careful not to double-count runoff from ice outlets included in your ROI, and then again ice outlets upstream of land outlets.

If your machine has < 12 GB of RAM, or you're maxing out what RAM you do have, try running this on a machine with more RAM. If you don't have access to one, let me know and I may be able to provide the subset and simplified data that you need.

**Comment by tarynblack** [comment]
Thanks @mankoff - RAM might be the issue, only 8GB on my machine. Working on running this on a bigger machine (might have to actually go back to the office, gasp!), will keep you posted.

**Comment by mankoff** [comment]
If you don't need the full time series, you could try deleting (or moving) various files out of the search folder. If it only opens 1 year or 1 decade, it would use less memory...

**Comment by tarynblack** [comment]
Was able to get this running on another machine, thank you!
