### ISSUE TITLE
xarray.core.merge.MergeError

### ISSUE THREAD

**Issue by ogersentia** [GEUS-Glaciology-and-Climate/freshwater#32]
Hello,

I am trying to run the given examples. So far, everything worked until specifying the discharge option:
python ./discharge.py --base ./freshwater --roi=-50.5,67.2 -q -d | (head -n1; grep -A9 "^2012-06-01")

I have an error with xarrray that I do not manage to solve:
...
line 141, in discharge
    self._discharge[key] = xr.open_mfdataset(file_list, combine="by_coords").rename({"runoff": key})
...
raise MergeError(
xarray.core.merge.MergeError: conflicting values for variable 'lat' on objects to be combined. You can skip this check by specifying compat='override'.

I attempted to add compat='override' in line 141, but id does not work with the combine option.

Have you already met this error? 
Can I provide any additional pieces of information?

Sentia

**Comment by mankoff** [comment]
I am not seeing that error. Probably due to versions. The README mentions the `environment.yml` file, but it is not untangled and checked into the repository. You can see the xarray (and other library) versions here https://github.com/GEUS-Glaciology-and-Climate/freshwater/blob/main/freshwater.org#python

**Comment by mankoff** [comment]
```python
In [1]: import xarray
In [2]: xarray.__version__
Out[2]: '0.20.2'
```

**Comment by mankoff** [comment]
The above is the version I just tested with on my local machine, different than version 0.15 in environment.yml used for the initial work.
