### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by markusReinert** [GEUS-Glaciology-and-Climate/freshwater#44]
Hi,

I suggest adding a LICENSE file to the repository, so that people know how they are allowed to use the script and how they can collaborate. My suggestion would be to use the MIT license. Another popular choice is GNU GPL.

Thanks!

Markus

**Comment by mankoff** [comment]
Thanks for suggesting this. I like MIT (because it's short) but I don't know who to assign Copyright to, so I went with LGPL. No need to put my name on it.
